import { existsSync, readFileSync, readdirSync, unlinkSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import type { Plugin } from "vite";
import type { ThemeRuntime } from "../runtime";
import { resolveDevHost } from "../run/dev-host";
import { clearSkip, isGitRepository, skipState } from "../utils/worktree";

export const MIXER_FORMAT_VERSION = 1;

const productionPrefix =
  "{% comment %}\n  IMPORTANT: This snippet is automatically generated by vite.\n  Do not attempt to modify this file directly, as any changes will be overwritten by the next build.\n{% endcomment %}\n";

function marker(form: "dev" | "prod"): string {
  return `{% comment %} vite-plugin-shopify-theme:mixer:${form}:v${MIXER_FORMAT_VERSION} {% endcomment %}\n`;
}

export function mixerForm(content: string): "dev" | "prod" | "unknown" {
  const devMarker = content.includes(marker("dev").trim());
  const prodMarker = content.includes(marker("prod").trim());
  const devBody = content.includes("/@vite/client");
  const prodBody = content.includes("asset_url");
  if (devMarker && devBody && !prodMarker && !prodBody) return "dev";
  if (prodMarker && prodBody && !devMarker && !devBody) return "prod";
  return "unknown";
}

// 把 Vite 接入 Shopify 主题，按构建态写出 mixer snippet：
// - dev（configureServer）：指向本地 dev server 的 script 标签。
// - build（generateBundle）：读 entry chunk 的 viteMetadata，改写为生产 asset_url /
//   stylesheet_tag；无需 manifest 中转。参见
//   https://vite.dev/guide/api-plugin#output-bundle-metadata
export default function mixer(runtime: ThemeRuntime): Plugin {
  const log = runtime.log("mixer");
  // 惰性求值：ctx 由 :config 的 config 钩子填充，工厂运行时尚未就绪。
  const snippetsPath = () => resolve(runtime.themePath, "snippets");
  const snippetViteMixer = () => resolve(snippetsPath(), runtime.snippet);

  // 写出 snippet = prefix + 各 tag。dev/build 共用此信封，仅差 prefix（build 带 disclaimer）。
  // 幂等：内容未变不落盘——mtime 一动，并行的 `shopify theme dev` 就会重传店铺、多刷一次页面。
  const writeSnippet = (tags: string[], prefix = ""): void => {
    const file = snippetViteMixer();
    const content = prefix + tags.join("\n") + "\n";
    if (existsSync(file) && readFileSync(file, "utf8") === content) {
      log.debug("snippet unchanged, skip write", file);
      return;
    }
    writeFileSync(file, content);
  };

  // 确保 layout/theme.liquid 引用了 mixer snippet：无引用时在 </head> 前注入 render 标签，
  // 免去接入时的手动一步。幂等：已有引用（任意引号、任意位置，含条件分支内的自定义写法）即跳过，
  // 不动用户的手工编排。持久写入——render 标签是主题的生产依赖（店铺端也要渲染产物），
  // 必须随主题仓库提交。
  const ensureRenderTag = (): void => {
    const layout = resolve(runtime.themePath, "layout", "theme.liquid");
    if (!existsSync(layout)) {
      log.error(
        `layout/theme.liquid not found; add {% render '${renderName(runtime.snippet)}' %} manually`,
      );
      return;
    }
    const name = renderName(runtime.snippet);
    const content = readFileSync(layout, "utf8");
    if (new RegExp(`\\{%-?\\s*render\\s+['"]${escapeRegExp(name)}['"]`).test(content)) {
      log.debug(`render tag already present in layout/theme.liquid`);
      return;
    }
    // 注入点：</head> 起始行之前，缩进随 </head> 再进两格。
    const head = /^([ \t]*)<\/head>/im.exec(content);
    if (!head) {
      log.error(`no </head> in layout/theme.liquid; add {% render '${name}' %} manually`);
      return;
    }
    writeFileSync(
      layout,
      content.slice(0, head.index) +
        `${head[1]}  {% render '${name}' %}\n` +
        content.slice(head.index),
    );
    log.info(`injected {% render '${name}' %} into layout/theme.liquid`);
  };

  return {
    name: "shopify-theme:mixer",
    enforce: "post",

    configureServer(server) {
      ensureRenderTag();

      server.httpServer?.once("listening", () => {
        log.debug("dev server", server.httpServer?.address());
        // 端口恒取实际监听地址（源自 vite.config 的 server.port，未指定则 Vite 自动选）。
        // 主机名由 devHost 选项定：默认 "127.0.0.1"（server.host 设成 wildcard 时也不外泄
        // 到 LAN IP——内嵌浏览器 / 代理常访问不了 LAN 地址）；"auto" 才按监听地址推导
        // （见 resolveDevHost，wildcard 时取 LAN IP，便于手机 / 局域网预览）；其余值原样使用。
        const addr = server.httpServer?.address();
        const port = addr && typeof addr === "object" ? addr.port : server.config.server.port;
        const host =
          runtime.options.devHost === "auto"
            ? resolveDevHost(addr && typeof addr === "object" ? addr.address : undefined)
            : runtime.options.devHost;
        const origin = `http://${host}:${port}`;

        // 单入口（ctx.entry，已是 root 相对、正斜杠），dev script 直接用；多入口待 entry 收多值。
        // /@vite/client 必须显式注入（Vite backend-integration 约定）：full-reload 与 HMR
        // 的 WebSocket 全靠它建立，不能指望 entry 模块图里恰好传递性加载了 client。
        const tags = [devScriptTag(origin, "@vite/client"), devScriptTag(origin, runtime.entry)];
        log.debug("dev snippet ->", snippetViteMixer());
        writeSnippet(tags, marker("dev"));
      });
    },

    // generateBundle 仅在 vite build 触发（dev 不触发），故无需再用 command 区分构建态。
    generateBundle(_options, bundle) {
      ensureRenderTag();

      if (runtime.options.worktree !== "off" && isGitRepository(runtime.themePath)) {
        const rel = `snippets/${runtime.snippet}`;
        if (skipState(runtime.themePath, rel) === "flagged") {
          clearSkip(runtime.themePath, rel);
          log.info(`skip-worktree cleared on ${rel} for production build`);
        }
      }

      const tags: string[] = [];

      // 每个 entry chunk：CSS 最前（渲染阻塞，越早进预扫描越好），随后预载其静态依赖
      // chunk（codeSplitting 拆出的初始 chunk，动态 import 不预载），最后 entry JS
      //（module script 天然 defer，放后无损）。
      // viteMetadata 由 Vite build 管线填充，enforce:"post" 确保此时已就绪。
      const preloaded = new Set<string>();
      for (const output of Object.values(bundle)) {
        if (output.type !== "chunk" || !output.isEntry) continue;
        output.viteMetadata?.importedCss.forEach((file) => tags.push(stylesheetTag(file)));
        for (const file of output.imports) {
          if (preloaded.has(file)) continue;
          preloaded.add(file);
          tags.push(modulePreloadTag(file));
        }
        tags.push(scriptTag(output.fileName));
      }

      if (tags.length === 0) {
        log.error("no entry chunk found in bundle");
        return;
      }

      log.debug("prod snippet ->", snippetViteMixer(), tags);
      writeSnippet(tags, marker("prod") + productionPrefix);
    },

    // 产物落盘后清理保留命名空间里的旧 chunk / async CSS：带中间段的 `vite-mixer.*.js|css`
    // 是内容寻址产物（见 :config 命名策略），不在本次 bundle 里的即上次构建残留。
    // entry 的 vite-mixer.js / vite-mixer.css 无中间段，不匹配；主题手工资产不受影响。
    writeBundle(_options, bundle) {
      const assetsPath = resolve(runtime.themePath, "assets");
      if (!existsSync(assetsPath)) return;
      const current = new Set(Object.keys(bundle));
      const stale = readdirSync(assetsPath).filter(
        (file) => /^vite-mixer\..+\.(js|css)$/.test(file) && !current.has(file),
      );
      for (const file of stale) unlinkSync(resolve(assetsPath, file));
      if (stale.length > 0) log.info(`pruned stale build outputs: ${stale.join(", ")}`);
    },
  };
}

// snippet 文件名 → render 标签用的 snippet 名（去 .liquid 后缀）
export function renderName(snippet: string): string {
  return snippet.replace(/\.liquid$/, "");
}

// 转义正则元字符，snippet 名可经选项自定义，不能直接拼进 RegExp
export function escapeRegExp(s: string): string {
  return s.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

// 生产 script 标签
function scriptTag(filename: string): string {
  return `<script src="{{ '${filename}' | asset_url }}" type="module"></script>`;
}

// 生产 stylesheet 标签
function stylesheetTag(filename: string): string {
  return `{{ '${filename}' | asset_url | stylesheet_tag }}`;
}

// 生产 modulepreload 标签（entry 的静态依赖 chunk）
function modulePreloadTag(filename: string): string {
  return `<link rel="modulepreload" href="{{ '${filename}' | asset_url }}">`;
}

// dev script 标签（/@vite/client 与各入口共用）
function devScriptTag(origin: string, path: string): string {
  return `<script src="${origin}/${path}" type="module"></script>`;
}
